In [1]:
import numpy as np


In [2]:
zeroarr=np.zeros(5)
zeroarr

array([0., 0., 0., 0., 0.])

In [20]:
zeroarr.dtype

dtype('int64')

In [21]:
zeroarr=np.zeros(5,dtype="int")
zeroarr

array([0, 0, 0, 0, 0])

In [23]:
array=np.array([[1,2,3,4],[5,6,7,8],[2,3,5,6]])
array


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 5, 6]])

In [25]:
array=np.array([[1,2,3,4],[5,6,7,8],[2,3,5,6]])
array.shape


(3, 4)

In [26]:
array=np.array([[1,2,3,4],[5,6,7,8],[2,3,5,6]])
array.dtype

dtype('int64')

In [27]:
array=np.array([[1,2,3],[4,5,6]])
np.swapaxes(array,0,1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
array=np.array([1,2,3,4])
array.max()

np.int64(4)

In [29]:
array=np.array([[1,2,3,4],[5,6,7,8],[2,3,5,6]])
array.reshape(4,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 2],
       [3, 5, 6]])

In [34]:
array=np.array([[1,2,3,4],[5,6,7,8],[2,3,5,6]])
array.sort(axis=0)
array


array([[1, 2, 3, 4],
       [2, 3, 5, 6],
       [5, 6, 7, 8]])

In [35]:
array=np.array([[1,2,3,4],[5,6,7,8],[2,3,5,6]])
array.sort(axis=1)
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 5, 6]])