In [ ]:
#Assignment 1
#Name: Aman Pathan
#Roll No : 104
#Class : TYIT-B
#Batch: B2

import numpy as np

In [ ]:
array=np.array([1,2,3,4,5,6,7]) # crreating a 1D Array 
print(array)   # Print array 
print(array[0])   # print 0th index element in array
print(array[1])
print(array[-1])
print(array[-2])

[1 2 3 4 5 6 7]
1
2
7
6


In [ ]:
array=np.array([1,2,3,4,5,6,7])
print(array.ndim)   # printing dimension of array
array1=np.array([[1,2,3],[4,5,6]])
print(array1.ndim)      # printing dimension of array

1
2


In [ ]:
array1=np.array([[1,2,3],[4,5,6]])      # creating 2D array
array2=np.array([[7,8,9],[10,11,12]])
print(array1)
print(array2)
print("_____________")
print(array1+array2)   # Additon of two 2D Array

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
_____________
[[ 8 10 12]
 [14 16 18]]


In [ ]:
array1=np.array([[1,2,3],[4,5,6]])
array2=np.array([[7,8,9],[10,11,12]])
print(array1)
print(array2)
print("_____________")
print(array1-array2)    # Substraction of two 2D Array

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
_____________
[[-6 -6 -6]
 [-6 -6 -6]]


In [ ]:
array1=np.array([[1,2,3],[4,5,6]])
array2=np.array([[7,8,9],[10,11,12]])
print(array1)
print(array2)
print("_____________")
print(array1*array2)    # Mult of two 2D Array

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
_____________
[[ 7 16 27]
 [40 55 72]]


In [ ]:
array1=np.array([[1,2,3],[4,5,6]])
array2=np.array([[7,8,9],[10,11,12]])
print(array1)
print(array2)
print("_____________")
print(array1/array2)    # div of two 2D Array

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
_____________
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [ ]:
array1=np.array([[1,2,3],[4,5,6]])
array2=np.array([[7,8,9],[10,11,12]])
print(array1)
print(array2)
print("_____________")
print(array1**array2)   # Power of two 2D Array

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
_____________
[[         1        256      19683]
 [   1048576   48828125 2176782336]]


In [ ]:
array3=np.arange(2,11)          #creating array by range function
print(array3)
print(array3.reshape(3,3))      # reshape array for printing

[ 2  3  4  5  6  7  8  9 10]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
array=np.array([1,2,3,4,5,6,7])
print(np.argmax(array))         #Print the max element index in Array
print(np.argmin(array))         #Print the min element index in Array

6
0


In [ ]:
array1=np.array([[1,2,3],[4,5,6]])

print(np.argmax(array1))                #Print the max element index in 2D Array
print(np.argmin(array1))                #Print the min element index in 2D Array

5
0
